[tool.poetry]
name = "vault"
version = "4.0.4"
description = "The main goal of the implementation is to simplify the use and interaction with Vault Server for my standard python projects. This module contains a set of methods for working with secrets and database engines in Vault."
authors = ["Bervinov Oleg <bervinov.ob@gmail.com>"]
maintainers = ["Bervinov Oleg <bervinov.ob@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "vault"}]
homepage = "https://github.com/obervinov/vault-package"
repository = "https://github.com/obervinov/vault-package"
documentation = "https://github.com/obervinov/vault-package/blob/main/README.md"
keywords = ["vault", "vault-api", "vault-server", "secrets", "vault-python"]
include = ["CHANGELOG.md"]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/obervinov/vault-package/issues"

[tool.poetry.dependencies]
python = "^3.12"
requests = "^2"
hvac = "^2"
logger = { git = "https://github.com/obervinov/logger-package.git", tag = "v2.0.4" }

[tool.poetry.group.dev.dependencies]
pylint = "^4"
flake8 = "^7"
pytest = "^9"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
