[tool.poetry]
name = "vault"
version = "2.0.2"
description = "This is an additional implementation compared to the hvac module. The main purpose of which is to simplify the use and interaction with vault for my standard projects. This module contains a set of methods for working with secrets and quickly configuring Vault."
authors = ["Bervinov Oleg <obervinov@pm.me>"]
maintainers = ["Bervinov Oleg <obervinov@pm.me>"]
license = "MIT"
readme = "README.md"
packages = [{include = "vault"}]
homepage = "https://github.com/obervinov/vault-package"
repository = "https://github.com/obervinov/vault-package"
documentation = "https://github.com/obervinov/vault-package/blob/main/README.md"
keywords = ["vault", "vault-api", "vault-server"]
include = ["CHANGELOG.md"]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/obervinov/messages-package/issues"

[tool.poetry.dependencies]
python = "^3.10"
hvac = "^1.1.0"
keyring = "^23.13.1"
SecretStorage = "^3.3.3"
python-dateutil = "^2.8.2"
logger = { git = "https://github.com/obervinov/logger-package.git", branch = "fix/v1.0.4" }


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
