[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "vault"
version = "2.0.0"
description = "This is an additional implementation compared to the hvac module. The main purpose of which is to simplify the use and interaction with vault for my standard projects. This module contains a set of methods for interacting and quickly installing Vault."
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.9"
authors = [
  { name="Bervinov Oleg", email="obervinov@pm.me" },
]
maintainers = [
    { name="Bervinov Oleg", email="obervinov@pm.me" },
]
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: Implementation :: CPython",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/obervinov/vault-package"
"Repository" = "https://github.com/obervinov/vault-package"
"Bug Tracker" = "https://github.com/obervinov/vault-package/issues"
"Documentation" = "https://github.com/obervinov/vault-package/blob/main/README.md"
"Changelog" = "https://github.com/obervinov/vault-package/blob/main/CHANGELOG.md"

[tool.poetry.dependencies]
python = "^3.6.2"
hvac = "^1.0.2"
logger = { git = "https://github.com/obervinov/logger-package.git", tag = "v1.0.1" }