[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "vault"
version = "2.0.1"
description = "This is an additional implementation compared to the hvac module. The main purpose of which is to simplify the use and interaction with vault for my standard projects. This module contains a set of methods for working with secrets and quickly configuring Vault."
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.9"
authors = [
  { name="Bervinov Oleg", email="obervinov@pm.me" },
]
maintainers = [
    { name="Bervinov Oleg", email="obervinov@pm.me" },
]
classifiers = [
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3.10",
        "Operating System :: OS Independent",
        "Intended Audience :: Developers",
        "Topic :: Software Development"
]

[project.urls]
"Homepage" = "https://github.com/obervinov/vault-package"
"Repository" = "https://github.com/obervinov/vault-package"
"Bug Tracker" = "https://github.com/obervinov/vault-package/issues"
"Documentation" = "https://github.com/obervinov/vault-package/blob/main/README.md"
"Changelog" = "https://github.com/obervinov/vault-package/blob/main/CHANGELOG.md"

[tool.poetry.dependencies]
python = "^3.6.2"
hvac = "^1.1.0"
keyring = "^23.13.1"
logger = { git = "https://github.com/obervinov/logger-package.git", tag = "v1.0.1" }

[tool.pytest.ini_options]
pythonpath = ["."]