name: Tests and checks

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - '!main'

jobs:
  changelog:
    uses: obervinov/_templates/.github/workflows/changelog.yaml@v1.0.12

  pylint:
    uses: obervinov/_templates/.github/workflows/pylint.yaml@v1.0.12

  pytest:
    uses: obervinov/_templates/.github/workflows/pytest-with-vault.yaml@v1.0.12

  pyproject:
    uses: obervinov/_templates/.github/workflows/pyproject.yaml@v1.0.12
