name: Create GitHub Release

on:
  push:
    branches: [main]
    paths: ['vault/**']

jobs:
  create-release:
    uses: obervinov/_templates/.github/workflows/create.release.yml@feature/github-actions
