name: Release

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  changelog:
    uses: obervinov/_templates/.github/workflows/changelog.yaml@v1.2.5

  pylint:
    uses: obervinov/_templates/.github/workflows/pylint.yaml@v1.2.5

  pytest:
    uses: obervinov/_templates/.github/workflows/pytest-with-vault.yaml@v1.2.5

  pyproject:
    uses: obervinov/_templates/.github/workflows/pyproject.yaml@v1.2.5

  create-release:
    uses: obervinov/_templates/.github/workflows/release.yaml@v1.2.5
    needs: [changelog, pylint, pytest, pyproject]
