name: Tests and checks

on:
  push:
    branches:    
      - '*'
      - '*/*'
      - '**'

jobs:
  pylint:
    uses: obervinov/_templates/.github/workflows/pylint.yml@feature/github-actions
  flake8:
    uses: obervinov/_templates/.github/workflows/flake8.yml@feature/github-actions
  package-version:
    uses: obervinov/_templates/.github/workflows/version.yml@feature/github-actions
